name: ann_shop_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter_localizations:
    #sdk: flutter
  #  firebase_analytics: ^5.0.1
  provider: ^3.1.0
  connectivity: ^0.4.3+7
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  webview_flutter: ^0.3.13
  flushbar: ^1.9.0
  extended_image: ^0.6.8
  intl: ^0.15.0
  flutter_html: ^0.11.0
  transparent_image: ^1.0.0
  url_launcher: ^5.2.7
  loading_more_list: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    # Image
    - assets/images/
    #- assets/images/locale/

    # Locale
    #- assets/locale/en/main.json
    #- assets/locale/vi/main.json
    #- assets/locale/en/common.json
    #- assets/locale/vi/common.json

    # Offline
    - assets/offline/