name: ann_shop_flutter
description: A new Flutter application.

version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter_localizations:
    #sdk: flutter
  provider: ^4.0.0
  connectivity: ^0.4.6+1
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  webview_flutter: ^0.3.18+1
  flushbar: ^1.9.1
  intl: ^0.16.0
  flutter_html: ^0.11.0
  url_launcher: ^5.4.1
  loading_more_list: ^1.0.2
  flutter_cache_manager: ^1.1.3
  cached_network_image: ^2.0.0-rc
  image_gallery_saver: ^1.2.2
  gesture_zoom_box: ^0.0.2
  firebase_core: ^0.4.3+1
  firebase_dynamic_links: ^0.5.0+9
  firebase_analytics: ^5.0.9
  onesignal_flutter: ^2.3.1
  #  share_extend: ^1.1.0
  esys_flutter_share: ^1.0.2
  share: ^0.6.3+5
  flutter_cupertino_date_picker: ^1.0.12
  qr_code_scanner: ^0.0.12
  permission_handler: ^4.1.0
  flutter_image_compress: ^0.6.5+1
  async: ^2.4.0
  path: ^1.6.4
  image_picker: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    # Image
    - assets/images/
    - assets/images/ui/

    # Locale
    #- assets/locale/en/main.json
    #- assets/locale/vi/main.json
    #- assets/locale/en/common.json
    #- assets/locale/vi/common.json

    # Offline
    - assets/offline/

    # Fonts
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf